benchmark/benchmark.py
Add warning in benckmark.py if required input token size not equal to real generated input token size.
Print out real input token size with the first token latency.
=> Add print info for real input token size in benchmark.py

src/utils/matmul_helper.h
So when matrix M<=8, we will use ig kernel to boost bf16 gemms, otherwise use oneDNN kernel.
From the performance data， we can see that with M=8， It can boost next token performance of BS=4/8, especially for BS=4.
This patch doesn't affect first token latency since the M of first latency is larger than 8.
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
</head>
<body link="#0563C1" vlink="#954F72">
batchsize | 1 | 2 | 4 | 8 | 16
-- | -- | -- | -- | -- | --
chatglm-6b
original M=2 | 30.58 | 31.03 | 63.56 | 67.61 | 78.38
M=7 | 29.54 | 32.58 | 41.28 | 68.14 | …
=> Update default M from 2 to 8

src/layers/attention.h, src/models/common_decoder.h
pass the max position info to QKPO class (which is the positional embedding), to make sure the positional embedding table is big enough.
=> Make configured max token size work

src/pytorch/CMakeLists.txt
Fix Python lib ERROR `undefined symbol: _ZNSt10filesystem18create_directoriesERKNS_4pathE` when `-DDEBUG=true`.
=> [CMake] Link stdc++fs in pt.so explicitly.

src/common/aligned_type.h, src/layers/attention.h, src/utils/decoder_util.h, src/utils/simple_mem_pool.h
Command: XFT_FAKE_MODEL=1 OMP_NUM_THREADS=32 mpirun -n 1 numactl -N 0 -m 0 ./build/example -m examples/model_config/llama-2-7b/ -t examples/model_config/llama-2-7b/tokenizer.model -d fp16 -l 1024 --output_len 10 --loop 10  : -n 1 numactl -N 1 -m 1 ./build/example -m examples/model_config/llama-2-7b/ -t examples/model_config/llama-2-7b/tokenizer.model -d fp16 -l 1024 --output_len 10 --loop 10
Server: a develop machine (perf may be not good)
Perf: ~40->~39ms
=> [perf] improve next token latency when (#threads >= 2 * #heads) by sharding the head into multiple splits

src/xfastertransformer/tools/__init__.py, src/xfastertransformer/tools/baichuan_convert.py, src/xfastertransformer/tools/chatglm2_convert.py, src/xfastertransformer/tools/chatglm_convert.py, src/xfastertransformer/tools/convert.py, src/xfastertransformer/tools/llama_convert.py, src/xfastertransformer/tools/opt_convert.py
Usage：
```
import xfastertransformer as xft
converter = xft.LlamaConvert()
converter("/data/llama-2-7b-chat","/data/llama-2-7b-chat-xft", "fp16")
```
Params:`input_dir, output_dir=None, dtype: str = "fp16", processes=8`
if `output_dir` is `None`, default use `input_dir` with a suffix `-xft`, like:
```
converter("/data/llama-2-7b-chat")
```
Support converter list:
```
LlamaConvert
ChatGLMConvert
ChatGLM2Convert
OPTConvert
BaichuanConvert
```
TODO:
- README
- Lazy import
- hugging face dependency version
=> [Tools] Add convert tools in xft.

src/xfastertransformer/__init__.py
Fix import issue:
```
>>> from xfastertransformer import AutoModel
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ImportError: cannot import name 'AutoModel' from 'xfastertransformer' (unknown location)
```
=> [API][Python] Fix AutoModel import error.

dockerfiles/Dockerfile, dockerfiles/Dockerfile.release
Fix _b2 module missing when run llama web demo in docker image.
=> [Dockerfile] Fix _b2 module missing.

.clang-format
Prefer "IndentPPDirectives=None" with following layout:
#if FOO
#if BAR
#include <foo>
#endif
#endif
=> clang-format: Remove duplicated IndentPPDirectives entry

src/common/bfloat16.h, src/kernels/rmsnorm_kernels.cpp, src/kernels/rmsnorm_kernels.h, src/layers/attention.h, src/layers/attn_baichuan.h, src/layers/attn_chatglm.h, src/layers/decoder_layer.h, src/layers/layer_norm.cpp, src/layers/layer_norm.h, src/layers/rms_norm.cpp, src/layers/rms_norm.h, src/models/chatglm.h, src/models/chatglm2.cpp, src/models/chatglm2.h, src/models/common_decoder.h, src/models/llama.cpp, src/models/llama.h, src/models/opt_decoder.h, src/models/qwen.h, src/utils/copy_util.h, src/utils/decoder_util.h, src/utils/type_selector.h
- Export InT, ImT, OutT in Attention
- Remove unused params in forwardAttention
- Move LayerNorm/RmsNorm class definition from include to layers
- Make RmsNorm supprort FP32 in, BF16 out.
- Correct GCC version for AVX512BF16
=> [Framework] Attention/LayerNorm/RmsNorm refactor/enhance to better support BF16 inference.

src/common/my_types.h, src/common/transformer_ctx.h, src/layers/attention.h, src/layers/mlp_llama.h, src/utils/matmul_helper.h
The case (config: Llama2-13b bs=32 in=2016) on xFT will cause coredump. It has been identified that the root cause is int32 overflow :
=> [common/utils] Fix bug of int32 overflow for larger size

src/layers/rotary_embedding_qwen.cpp, src/layers/rotary_embedding_qwen.h
Fix issue [195](https://github.com/intel/xFasterTransformer/issues/195)
=> Add base_initial to store the original base passed from config

src/layers/attn_baichuan.h, src/models/baichuan.cpp, src/models/baichuan.h, src/xfastertransformer/tools/baichuan_convert.py
Fix the bug reported by issue #209 
For Baichuan2-13B-Chat v2.0
input prompt:
prompt ="""已知信息：
了 label smoothing 和 mixup 微调之后的模型做了权重上的线性加权。实验结果如
表 3.2 所示。结果表明，BANG 算法有效的提高了 WiSE-FT 算法的效果。特别的，
BANG(LS+Mixup)在五个OOD数据集上比现有的最优算法WiSE-FT高出1.9%。
表3.2 在ImageNet上微调ViT-B/16的效果
Methods ModelAveraging IN IN-V2 IN-R IN-A IN-S ObjectNet AvgOOD
ZIN 与现有的几种方法进行了比较:ERM、IRM[58]、EIIL[71]、HRM[70]和 LfF[81]。
对于IRM，本文提供了ground-truth环境划分，并将其性能作为一个上界。LfF试
图通过从错误指定的浅层神经网络样本中直接采用 boosting 来学习一个鲁棒的模
型。而且LfF仅适用于分类任务。
5.4.1 房价预测任务
本实验考虑了来自Kaggle的真实房屋销售价格回归数据集。目标变量是房价，
每个样本包含17维度的特征，如房子的建成年份、卧室数量等。数据集根据构建
BANG(Mixup+LS) Yes 81.6 73.1 79.7 58.2 54.8 58.9 64.9
3.5 小结
本节研究了为什么集成算法具有优越的 OOD 性能。对 WiSE-FT 的实证分析，
加上理论见解，表明虚假特征的多样化改善了模型的泛化性能。进一步的，笔者通
过缓解微调模型的过度自信问题改进了WiSE-FT。
20 
根据上述已知信息，简洁和专业的来回答用户的问题。如果无法从中得到答案，
请说 …
=> [models][layers/tools] Refine and bugfix for baichuan models

CMakeLists.txt, cmake/onednn.cmake, examples/cpp/CMakeLists.txt, include/dtype.h, src/common/my_types.h, src/models/chatglm2.cpp, src/models/chatglm2.h, src/models/chatglm3.h, src/models/common_decoder.h, src/models/models.cpp, src/pytorch/CMakeLists.txt, src/utils/matmul_helper.h
Step 1） Install dpc++ compiler:
```bash
sh l_dpcpp-cpp-compiler_p_2024.0.0.49524_offline.sh
```
Step 2） Install conda env:
```bash
mkdir -p ~/miniconda3
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
rm -rf ~/miniconda3/miniconda.sh
~/miniconda3/bin/conda init bash
~/miniconda3/bin/conda init zsh
conda --version
conda create --name xft python=3.8
conda activate xft
```
Step 3) Install oneccl and dependencies:
```bash
git clone https://github.com/intel/xFasterTransformer.git
cd xFasterTransformer/3rdparty/
sh prepare_oneccl.sh
pip install -r ../requirements.txt
```
Step 4) Initialize env:
```bash
cd xFasterTransformer/
mkdir build && cd build
conda activate xft
source …
```
=> [kernel] Add ICX compiler.

src/comm_helper/comm_helper.cpp, src/models/common_decoder.h, src/models/models.cpp, src/utils/verbose.h
There are 2 methods to assign GPU cards to map into MPI processes.
Method 1) Assign Sequentially(`XFT_ENGINE=GPU`), like MPI process 0 maps to GPU card 0, MPI process 1 maps to GPU card 1...
```bash
XFT_ENGINE=GPU XFT_PIPELINE_STAGE=1 OMP_NUM_THREADS=12 ENABLE_CAT_MLP=1 mpirun \
-n 1 numactl --all -C 48-59 -m 1 ./example --model /data/qwen-1_8b-xft/ --token /data/qwen-1_8b-hf/tokenizer_config.json --dtype fp16 --loop 1 --input_len 16 --output_len 16 : \
-n 1 numactl --all -C 60-71 -m 1 ./example --model /data/qwen-1_8b-xft/ --token /data/qwen-1_8b-hf/tokenizer_config.json --dtype fp16 --loop 1 --input_len 16 --output_len 16 : \
-n 1 numactl --all -C 72-83 -m 1 ./example --model /data/qwen-1_8b-xft/ --token /data/qwen-1_8b-hf/tokenizer_config.json --dtype fp16 --loop 1 --input_len 16 …
```
=> [Env] Add XFT_ENGINE env variable.

src/layers/rotary_embedding_qwen.cpp
Link with the Issue #229 Qwen Segmentation Fault after logN PR merged.
=> [Fix] Add parameter check for logN and NTK rotary embedding of QWEN

cmake/mkl.cmake
When the cache becomes invalid, it will lead to the re-download and installation of MKL. The size of the `mkl-static` file is 200+MB, and it may also cause the existing MKL dependencies in the environment to become invalid.
=> [CMake] Remvoe force reinstall for mkl dependencies.

include/dtype.h, src/CMakeLists.txt, src/common/float16.h, src/layers/attention.h, src/layers/dist_linear.h, src/layers/layer_norm.cpp, src/layers/layer_norm.h, src/layers/rms_norm.cpp, src/layers/rms_norm.h, src/layers/token_embedding.h, src/models/baichuan.cpp, src/models/chatglm.cpp, src/models/chatglm2.cpp, src/models/common_decoder.h, src/models/llama.cpp, src/models/opt_decoder.cpp, src/models/qwen.cpp, src/models/yarn_llama.cpp, src/utils/copy_util.h, src/utils/weight_util.h, src/xfastertransformer/tools/qwen_convert.py, tests/ut/CMakeLists.txt
qwen 7b loading time from `24s` to `16s`;
qwen 72b loading time from `517s` to `400s`;
=> [Tools] Accelerate model loading.

src/models/opt_decoder.cpp
Load beta weights, which is omitted by previous change.
=> Fix Opt issue

.github/workflows/xft_PR.yml, benchmark/benchmark.py, benchmark/run_benchmark.sh, ci/test_case, ci_build, src/kernels/token_embedding_kernels.cpp, src/kernels/token_embedding_kernels.h, src/layers/token_embedding.h, src/utils/messenger.h, tests/ut/CMakeLists.txt, tests/ut/messenger_test.cpp, tests/ut/token_embedding_test.cpp
this PR contains several updates:
1. Force check the results of UT. If UT fails, it will block the execution of CI;
Some UTs currently have not passed the test and need to wait for subsequent PR fixes.
```shell
vim ci_build
...
ut() {
...
#Todo(marvin): delete me when the case is ready.
if [[ "$file" == "./beam_search_test" ]]; then
Warning "Bypass the fail case of $file."
continue
fi
if [[ "$file" == "./kv_reorder_test" ]]; then
Warning "Bypass the fail case of $file."
continue
fi
if [[ "$file" == "./layers_mlp_test" ]]; then
Warning "Bypass the fail case of $file."
continue
fi
if [[ "$file" == "./rotary_embedding_test" ]]; then
Warning "Bypass the fail case of $file."
continue
fi
##################################################
...
```
2. The test case required for end-to-end testing …
=> [CI] Check for UT status.

benchmark/run_benchmark.sh, src/common/kvcache_tensor.h, src/layers/attention.h, src/models/env_config.cpp, src/models/kvcache_manager.cpp, src/utils/decoder_util.h, src/utils/matmul_helper.h, src/utils/messenger.h, src/utils/shm_reduction.cpp, src/utils/shm_reduction.h
Transpose KVCache with env var "ENABLE_KV_TRANS" for long sequence
Tune addreduce between shm and ccl for faster comm
| workload | baseline-2s | opt-2s |
| --------------- | --------------- | --------------- |
| llama-2-13b bs24 in512 bf16 (SPR+HBM) | 350ms | 90ms |
| llama-2-70b bs32 in4096 bf16 (SPR) | 1300ms | 640ms |
=> Add KVCache trans for long sequence && tuned comm for faster Addreduce

src/xfastertransformer/tools/qwen_convert.py
The current Qwen-72B model conversion process consumes approximately 282GB of memory, which far exceeds the configuration of the machines currently used by the client. This PR modify the conversion method to reduce memory usage to around 20~30GB.
=> [Fix] Reduce convert memory usage.

README.md, ci/test_case, requirements.txt, src/common/transformer_ctx.h, src/kernels/rmsnorm_kernels.cpp, src/layers/attention.h, src/layers/mlp_llama.cpp, src/layers/mlp_llama.h, src/layers/mlp_standard.h, src/layers/token_embedding_gemma.h, src/models/common_decoder.h, src/models/gemma.cpp, src/models/gemma.h, src/models/models.cpp, src/utils/debugger.h, src/utils/decoder_util.h, src/utils/matmul_helper.h, src/xfastertransformer/__init__.py, src/xfastertransformer/tools/__init__.py, src/xfastertransformer/tools/llama_convert.py
=> [Model] Add gemma model support.

README.md, examples/cpp/example.cpp
1. add gemma model into example.cpp;
2. Verified the Gemma series models, including CodeGemma, Gemma1.1, and Gemma. Due to the same structure, all three models are supported, and they have been validated in examples and web demos. Currently, the test routines for these models are consistent with Gemma.
https://huggingface.co/collections/google/codegemma-release-66152ac7b683e2667abdee11
https://huggingface.co/collections/google/gemma-release-65d5efbccdbb8c4202ec078b
=> [example] add gemma model support with example.

src/comm_helper/CMakeLists.txt
Fix build issue in no oneccl environment.
=> [CMake] Add oneccl build depends for comm_helper.

src/pytorch/CMakeLists.txt, src/xfastertransformer/__init__.py, src/xfastertransformer/env.py
libiomp can be set by `export $(python -c 'import xfastertransformer as xft; print(xft.get_env())')`
=> [Python] Add `get_env()` to get LD_PRELOAD set.

include/models.h, src/models/models.cpp, src/pytorch/auto_model.h, src/xfastertransformer/automodel.py
Master and slaves should both run according to the following workflow:
```Python
while True:
model.set_input_cb()
model.forward_cb()
model.free_seqs()
```
=> [Distribute] Add distribute support for continuous batching api.

src/utils/matmul_helper.h
This PR supports bf16_int8/bf16_int4 datatype for int8/int4 GPTQ model.
=> [Common]Add INT8/UINT4 to BF16 weight convert

CMakeLists.txt, cmake/onednn.cmake, src/utils/matmul_helper.h, src/utils/type_selector.h
need export env DNNL_MAX_CPU_ISA=AVX512_CORE_AMX_FP16 when running
=> [Feature] Enable AMX FP16 on next generation CPU

benchmark/benchmark.py, benchmark/run_benchmark.sh
please rename prompts file extension to .sonnet.
=> Add sonnet dataset support in benchmark.py
