intel/xFasterTransformer

benchmark/benchmark.py, examples/pytorch/demo.py
add build_input for chatglm/chatglm2 chat mode in demo.py and benchmark.py
use --chat True to enable chatglm/chatglm2 chat mode. otherwise using stream generate for inference
=> Add support for chatglm/chatglm2 chat mode

src/layers/attention.h, tools/llama_convert.py
grouped-query attention for Llama2
fix llama convert tool
=> [feature][layer][attn] grouped-query attention for Llama2

include/models.h, src/models/models.cpp, src/pytorch/auto_model.h, src/xfastertransformer/automodel.py
When Master exits, it will send a ZERO configuration to Slaves.
Then Slaves will revieve it in config() and exit directly ( exit(0) )
=> [MPI] Add exit functions in MPI mode

src/common/transformer_ctx.h, src/layers/attention.h, src/layers/mlp_chatglm2.h, src/layers/mlp_llama.h, src/layers/mlp_standard.h, src/utils/compile_util.h, src/utils/decoder_util.h, src/utils/matmul_helper.h, src/utils/split_util.h, src/utils/weight_util.h
support the imbalance split.
for example, split 40 heads in LLama13B into 3 ranks, then 40 heads will be split into 14, 13, and 13.
=> [TP] imbalance split support

CMakeLists.txt, src/CMakeLists.txt
=> [3rdparty] Remove mklml dependency.

tools/opt_convert.py
Fix issue https://github.com/intel/xFasterTransformer/issues/90
=> [Tools] Fix opt convert tool issue.

dockerfiles/Dockerfile, dockerfiles/Dockerfile.release
Python won't be detected by cmake if not added into PATH
=> [Dockerfile] Add python into PATH.

benchmark/README.md, benchmark/benchmark.py, benchmark/run_benchmark.sh
Got llama-2-7b result on HBM flat snc4:
./run_benchmark.sh -m llama-2-7b -d bf16_fp16 -bs 1 -b 1 -in 32 -out 32
==================================================llama-2-7b Final Performance==================================================
Inference Latency:      0.88 s
First token Avg Latency:        100.45 ms
Next token Max Latency: 25.24 ms
Next token Min Latency: 24.89 ms
Next token P90 Latency: 25.18 ms
Next token Avg Latency: 25.01 ms
Next token Latency:     25.18 ms
Which is on par with previews results.
=> [benchmark] Expose all parameters

src/xfastertransformer/__init__.py
Fix issue https://github.com/intel/xFasterTransformer/issues/153
=> [Fix] comm_helper can't found issue.

examples/cpp/example.cpp
Benchmarked that the 'first' next-token latency will be larger than the average next-token latency generally.
Average next-token latency could be the more reasonable number to reflect the latency instead of the 'first' next-token latency.
=> [Demo] use average next-token latency as the info to user.

examples/cpp/example.cpp, examples/pytorch/demo.py, include/abstract_searcher.h, include/models.h, src/models/models.cpp, src/pytorch/auto_model.h, src/searchers/beam_search.cpp, src/searchers/greedy_search.cpp, src/searchers/greedy_search.h, src/searchers/sample_search.cpp, src/searchers/sample_search.h, src/searchers/search_utils.cpp, src/searchers/search_utils.h, src/xfastertransformer/automodel.py
Model: Qwen -7B
Input:`以明天会更好为主题写500字作文:`
=========No repetition penalty Output=========
```
以明天会更好为主题写500字作文:明天会更好
明天会更好，这是一个永恒的信念，也是一个美好的愿望。明天会更好，明天会更好，明天会更好，明天会更好，明天会更好，明天会更好，明天会更好，明天会更好，明天会更好，明天会更好，明天会更好，明天会更好，明天会更好，明天会更好，明天会更好，明天会更好，明天会更好，明天会更好
，明天会更好，明天会更好，明天会更好
```
=========repetition penalty=1.1 Output=========
```
以明天会更好为主题写500字作文:明天会更好
明天会更好，这是一个永恒的信念。无论何时何地，只要心中有这个信念，就会有无穷的力量去战胜一切困难。
记得有一次，我在做数学题时遇到了一个难题，我左思右想，怎么也想不出来。正当我准备放弃的时候，我想起了“明天会更好”这句话，于是我又重新振作起来，继续思考。经过一番努力，我终于解出了这道难题。这件事让我深刻地体会到了“  
```
=> [Search] Add repetition penalty.

src/utils/matmul_helper.h
=> [kernel] Fix w8a8 crash issue due to buffer size not big enough

benchmark/run_benchmark.sh
https://github.com/intel/xFasterTransformer/issues/152
=> [Benchmark] Avoid float in core pre numa calculation.

examples/cpp/example.cpp, src/common/transformer_ctx.h, src/layers/attn_rope_scaling.h, src/layers/yarn_scaled_rotary_embedding.cpp, src/layers/yarn_scaled_rotary_embedding.h, src/models/common_decoder.h, src/models/models.cpp, src/models/yarn_llama.cpp, src/models/yarn_llama.h, src/xfastertransformer/__init__.py, src/xfastertransformer/tools/__init__.py, src/xfastertransformer/tools/yarn_llama_convert.py, tools/yarn_llama_convert.py
transformers==4.34.1
tokenizer use_fast=True
The customer-provided model only come out garbled output after  being interfered with "randn". The fp32 results align consistently with PyTorch:
xFT:
Pytorch:
while the bf16-type results differ on xFT:
=> [Model][SecLLM] Add SecLLM(YaRN-Llama) model support

include/abstract_searcher.h, include/models.h, src/models/models.cpp, src/pytorch/auto_model.h, src/pytorch/pytorch_warpper.cpp, src/searchers/beam_search.cpp, src/searchers/beam_search.h, src/searchers/greedy_search.cpp, src/searchers/greedy_search.h, src/searchers/sample_search.cpp, src/searchers/sample_search.h, src/searchers/search_utils.cpp, src/searchers/search_utils.h, src/xfastertransformer/automodel.py
When the model says a certain word, it can make you cover its mouth.
=> [Generation] Add stop_words_ids generation config.

cmake/xdnn.cmake
- Add small_sgemm_f32bf16bf16.
- Add small_sgemm_f32f16bf16.
=> [xDNN] Release v1.4.3.

src/kernels/gemm_kernel_ext.cpp, src/kernels/gemm_kernel_ext.h, src/layers/attention.h, src/layers/mlp_llama.h, src/models/kvcache_manager.cpp, src/utils/decoder_util.h, src/utils/intrinsics_util.h, src/utils/messenger.h, src/utils/shm_reduction.cpp, src/utils/type_selector.h
rough testing shows first token latency could drop from ~800ms -> ~660ms on a 48 core dev machine (llama-7B, input token size = 1k)
=> [Layer] Support pure full-link BF16 LLaMa model.

examples/model_config/qwen-14b/config.ini, examples/model_config/qwen-1_8b/config.ini, examples/model_config/qwen-72b/config.ini, examples/model_config/qwen-7b/config.ini
Config file change introduced in https://github.com/intel/xFasterTransformer/pull/189/files#diff-ecfd9cbd6dca35aebdbf30e02ba312e030770ffc5bf32983a0190899ecf8dddd
=> [Example] Add seq_length in qwen fake config.ini

src/layers/rotary_embedding_qwen.cpp
using seqLen + pastSeqLen to calculate new base
link to #220
=> fix issue #220

examples/pytorch/demo.py
Add llama 2 Chat mode support. Demo will skip prompt when `--chat true`.
=> [Example] Add llama2 chat support in Cli demo.

examples/web_demo/requirements.txt
Update gradio_client to 0.10.1 to match gradio. Remove torch since it has been included in xft's dependencies.
=> [Dependency] Update web demo requirement.

benchmark/benchmark.py, benchmark/run.sh, benchmark/run_benchmark.sh, benchmark/run_benchmark_dist.sh, ci_build, docs/en/dist_demo.md, docs/zh/dist_demo.md, examples/model_config/baichuan2-13b/config.ini, examples/model_config/baichuan2-7b/config.ini, examples/model_config/chatglm2-6b/config.ini, examples/model_config/chatglm3-6b/config.ini, examples/model_config/llama-13b/config.ini, examples/model_config/llama-2-7b/config.ini, examples/model_config/llama-30b/config.ini, examples/model_config/llama-65b/config.ini, examples/model_config/opt-6.7b/config.ini, examples/model_config/qwen-7b/config.ini
current CI output looks like this.
=> [Benchmark] Modify CPU affinity logic, add CI prompt output.

examples/model_config/qwen-14b/config.ini, examples/model_config/qwen-1_8b/config.ini, examples/model_config/qwen-72b/config.ini, examples/model_config/qwen-7b/config.ini, src/common/transformer_ctx.h, src/layers/attn_qwen.h, src/layers/rotary_embedding_qwen.cpp, src/layers/rotary_embedding_qwen.h, src/models/common_decoder.h, src/utils/weight_util.h, src/xfastertransformer/tools/qwen_convert.py
Sync with Torch vervion.
When seq_length is larger than max support seq length, we reduce seq_length to max support seq length.
=> Issue qwen72b seq length

ci_build, src/common/kvcache_tensor.h, src/models/kvcache_manager.cpp, tests/ut/kv_reorder_test.cpp
moved reorder from KVCacheManager to KVCacheTensor, and removed getData() in KVCacheTensor.
=> [KVCache] KV Cache refactor and related unit test case fix

docs/en/dev_guide.md
=> Add section 1 & 2 to dev guide

include/abstract_decoder.h, include/models.h, src/models/common_decoder.h, src/models/hybrid_model.h, src/models/models.cpp, src/searchers/sampling_params.h
Replace `Model::input()` and `Model::config()` with `Model::set_input()`.
Refactor `Decoder.forward()` params to `std::vector<xft::SequenceMeta *> &seq, bool logits_all = false`.
=> [Model] add interface for seq meta.

src/kernels/layernorm_kernels.cpp, tests/ut/layers_norm_test.cpp, tests/ut/rms_norm_test.cpp
+ Add FP16 UTs for layernorm and rmsnorm.
=> [API] Add layernorm FP16 support;
